CREATE DATABASE AMAZON_CLONE;
USE AMAZON_CLONE;
CREATE TABLE PRODUCTS(ID INT,PROD_NAME VARCHAR(50),PROD_PRICE INT,DISC_PRICE INT);
DESC PRODUCTS;
CREATE TABLE USER_ACCOUNTS(ID INT PRIMARY KEY,NAME VARCHAR(50),EMAIL VARCHAR(50),MOBILE bigint,PRIME VARCHAR(10));
DESC USER_ACCOUNTS;
CREATE TABLE ORDERS(ID INT PRIMARY KEY,PROD_NAME VARCHAR(50),FINAL_PRICE INT,ADDRESS VARCHAR(100));
DESC ORDERS;
CREATE TABLE PRIME_ACCOUNTS(ID INT PRIMARY KEY,NAME VARCHAR(50),MOBILE bigint,EMAIL VARCHAR(50),PRIME VARCHAR(10));

CREATE TABLE USER_ORDERS(
                  ORDER_ID INT PRIMARY KEY,
                  PRODUCT_NAME VARCHAR(50),
                  PRICE INT NOT NULL,
                  UID INT NOT NULL,
                  FOREIGN KEY(UID) REFERENCES USER_ACCOUNTS(ID));
				
CREATE TABLE PRIME_ORDERS(
                  ORDER_ID INT PRIMARY KEY,
                  PRODUCT_NAME VARCHAR(50),
                  PRICE INT NOT NULL,
                  UID INT NOT NULL,
                  FOREIGN KEY(UID) REFERENCES PRIME_ACCOUNTS(ID));
                  

