CREATE DATABASE CD1;
USE  CD1;
CREATE TABLE USER1(ID INT,NAME VARCHAR(50),MOBILE bigint,COURSE VARCHAR(10));
DESCRIBE USER1;
ALTER TABLE USER1
ADD EMAIL VARCHAR(100);
DESC USER1;
ALTER TABLE USER1
ADD (X1 INT,X2 INT);
ALTER TABLE USER3
ADD(DISC_PRICE INT,MFG_DATE DATE,EXP_DATE DATE);
DESC USER3;
ALTER TABLE USER1
DROP COLUMN X1;
DESC USER1;
ALTER TABLE USER1
MODIFY COLUMN MOBILE INT;
DESC USER1;
DROP TABLE USER2;
SELECT * FROM USER1;
SELECT ID,NAME FROM USER1;