CREATE DATABASE cd2;
USE cd2;
CREATE TABLE EMP(ID INT PRIMARY KEY auto_increment,
                  EMP_NAME VARCHAR(50) NOT NULL,
                  MOBILE BIGINT UNIQUE,
                  ADDRESS VARCHAR(100) DEFAULT "HYDERABAD");

INSERT INTO EMP(EMP_NAME,MOBILE) VALUES("ADITYA",9392567623);
SELECT * FROM EMP;

CREATE TABLE EMP2(ID INT PRIMARY KEY auto_increment,
				  EMP_NAME VARCHAR(50) NULL,
                  AGE INT NOT NULL,
                  SALARY INT NOT NULL,
                  ADDRESS VARCHAR(100),
                  CHECK(AGE>=18 AND SALARY>=10000 AND ADDRESS IN ("HYDERABAD","VISAKHAPATNAM")));
DROP TABLE EMP2;
INSERT INTO EMP2(AGE,SALARY,ADDRESS) VALUES(18,10000,"HYDERABAD");
INSERT INTO EMP2(AGE,SALARY,ADDRESS) VALUES(18,10000,"VISAKHAPATNAM");
INSERT INTO EMP2(EMP_NAME,AGE,SALARY,ADDRESS) VALUES("ADITYA",18,10000,"NELLORE");
INSERT INTO EMP2(EMP_NAME,AGE,SALARY,ADDRESS) VALUES("ADITYA",18,10000,"VISAKHAPATNAM");
SELECT * FROM EMP2;


