CREATE DATABASE DML;
USE DML;
CREATE TABLE EMPLOYEE(ID INT,NAME VARCHAR(50),SALARY INT);
INSERT INTO EMPLOYEE(ID,NAME,SALARY) VALUES(1,"ADITYA",50000);
INSERT INTO EMPLOYEE VALUES(2,"SAI",40000);
INSERT INTO EMPLOYEE(NAME,SALARY,ID) VALUES("KUMAR",30000,3);
INSERT INTO EMPLOYEE VALUES(4,"NAME 1",20000),(5,"NAME 2",10000),(6,"NAME 3",20000);
SELECT * FROM EMPLOYEE;
CREATE TABLE MAXSAL(ID INT,NAME VARCHAR(50));
INSERT INTO MAXSAL(SNO,TITLE) SELECT ID,NAME FROM EMPLOYEE WHERE SALARY>=30000;
SELECT * FROM MAXSAL;
SET SQL_SAFE_UPDATES=0;
UPDATE EMPLOYEE SET SALARY=25000 WHERE ID=4;
DELETE FROM EMPLOYEE WHERE ID=5;

CREATE TABLE PRODUCTS(
      ID INT KEY AUTO_INCREMENT,
      NAME VARCHAR(50) NOT NULL,
      PRICE INT NOT NULL DEFAULT 0);
DESC PRODUCTS;

INSERT INTO PRODUCTS VALUES(1,"SAI",10000);
INSERT INTO PRODUCTS (NAME,PRICE) VALUES("NAME",5000);
SELECT * FROM PRODUCTS;
