USE CODEGNAN;

CREATE TABLE USERS(
            USERID INT PRIMARY KEY NOT NULL,
            NAME VARCHAR(50),
            AGE INT NOT NULL);

CREATE TABLE ORDERS(
			ORDER_ID INT PRIMARY KEY NOT NULL,
            PRODUCT_NAME VARCHAR(50),
            PRICE INT DEFAULT 0,
            UID INT NOT NULL,
            FOREIGN KEY(UID) REFERENCES USERS(USERID)
		);
            
INSERT INTO USERS VALUES(1,"ADITYA",21);
INSERT INTO USERS VALUES(2,"SAI",30);
INSERT INTO ORDERS VALUES(101,"SOAP",100,1);
INSERT INTO ORDERS VALUES(102,"TOOTHBRUSH",50,1);
SELECT * FROM USERS;
SELECT * FROM ORDERS; 