CREATE DATABASE STORE;
USE STORE;
CREATE TABLE FRUIT_SHOP(
      ID INT KEY auto_increment,
      NAME VARCHAR(50) NOT NULL,
      QUANTITY INT NOT NULL,
      COUNTER_NO INT NOT NULL);

INSERT INTO FRUIT_SHOP(ID,NAME,QUANTITY,COUNTER_NO) VALUES(1,"APPLE",2,101);
INSERT INTO FRUIT_SHOP(NAME,QUANTITY,COUNTER_NO) 
VALUES("MANGO",5,102),("MANGO",7,104),("APPLE",3,103),("WATERMELON",5,101),("PINEAPPLE",4,102);

SELECT * FROM FRUIT_SHOP;

CREATE TABLE APPLE_STORE(ID INT KEY AUTO_INCREMENT ,QUANTITY INT NOT NULL,COUNTER_NO INT NOT NULL);
INSERT INTO APPLE_STORE(QUANTITY,COUNTER_NO) SELECT QUANTITY,COUNTER_NO FROM  FRUIT_SHOP WHERE NAME="APPLE";
SELECT * FROM APPLE_STORE;

CREATE TABLE MANGO_STORE(ID INT KEY AUTO_INCREMENT ,QUANTITY INT NOT NULL,COUNTER_NO INT NOT NULL);
INSERT INTO MANGO_STORE(QUANTITY,COUNTER_NO) SELECT QUANTITY,COUNTER_NO FROM  FRUIT_SHOP WHERE NAME="MANGO";
SELECT * FROM MANGO_STORE;




