USE cd1;

CREATE TABLE EMP5(ID INT,EMPNAME VARCHAR(50),CITY VARCHAR(50));

INSERT INTO EMP5 VALUES(1,"SAI VARDHAN","LONDAN"),(2,"VISHNU VARDHAN","LONDEN"),(3,"VENKAT","INDIA"),(4,"VENKOT","INDIA");

SELECT CONCAT(EMPNAME," PLACE IS ",CITY) AS DETAILDS FROM EMP5;

SELECT CONCAT_WS(",",EMPNAME,CITY) AS DETAILS FROM EMP5;

SELECT LOWER("ADITYA");

SELECT EMPNAME,LOWER(EMPNAME) AS LOWER FROM EMP5;

SELECT CITY,LENGTH(CITY) AS NAMELEN FROM EMP5;

SELECT CITY,CHAR_LENGTH(CITY) AS CHARLEN FROM EMP5;

SELECT SUBSTRING("ADITYA",2,5) AS SUBSTR;

SELECT EMPNAME,SUBSTRING(EMPNAME,2,5) AS SUBSTR FROM EMP5;

SELECT REVERSE("ADITYA");

SELECT EMPNAME,REVERSE(EMPNAME) AS REVSTR FROM EMP5;

SELECT REPLACE("SAI VARDHAN","VARDHAN","KUMAR") AS REPLACED;

SELECT EMPNAME,REPLACE(EMPNAME,"VARDHAN","KUMAR") AS EMPNAME FROM EMP5;
SELECT * FROM EMP5;
SELECT EMPNAME AS VARD FROM EMP5
WHERE EMPNAME LIKE ("%DHAN");

SELECT EMPNAME AS SAI FROM EMP5
WHERE EMPNAME LIKE ("S_I%");